platform :ios, :deployment_target => "5.0"

pod 'ObjectiveSugar', :path => '../'

target :ObjectiveSugarTests, :exclusive => true do
  pod 'Kiwi', :inhibit_warnings => true
end

begin
  require 'slather'
  Slather.prepare_pods(self)
rescue LoadError
  puts 'Slather has been disabled (not installed).'
end